// packages/core/src/crypto/elgamal.test.ts
//
// Story 3.2 Task 2: roundtrip test for the extracted elgamalProve + verifyElGamal.

import { describe, it, expect } from "vitest";
import { ristretto255 } from "@noble/curves/ed25519.js";

import {
  G,
  H,
  RISTRETTO_N,
  bytesFromBigIntLE,
  elgamalProve,
  verifyElGamal,
  bytesToHex,
} from "./index.js";

// Fixture constants matching SPIKE-1 aggregate test.
const AGG_SK = 12345n;
const ENTRY_A_AMOUNT = 40000n;
const ENTRY_A_BLINDING = 11111n;
const ENTRY_B_AMOUNT = 30000n;
const ENTRY_B_BLINDING = 22222n;
const AGG_AMOUNT = ENTRY_A_AMOUNT + ENTRY_B_AMOUNT;
const AGG_BLINDING = ENTRY_A_BLINDING + ENTRY_B_BLINDING;

function buildAggregatePoints() {
  const Hp = H();
  const Gp = G();
  const pk = Gp.multiply(AGG_SK);
  const c1A = Gp.multiply(ENTRY_A_BLINDING).add(Hp.multiply(ENTRY_A_AMOUNT));
  const dhA = pk.multiply(ENTRY_A_BLINDING);
  const c1B = Gp.multiply(ENTRY_B_BLINDING).add(Hp.multiply(ENTRY_B_AMOUNT));
  const dhB = pk.multiply(ENTRY_B_BLINDING);
  return { pk, c1: c1A.add(c1B), dh: dhA.add(dhB) };
}

describe("elgamalProve + verifyElGamal (packages/core/crypto/elgamal)", () => {
  it("prove → verify roundtrip passes for the aggregate fixture", () => {
    const { pk, c1, dh } = buildAggregatePoints();
    const dst = new Uint8Array(0);
    const r1 = 1234n;
    const r2 = 5678n;

    const proof = elgamalProve(dst, AGG_BLINDING, AGG_AMOUNT, pk, c1, dh, r1, r2);

    expect(proof).toBeInstanceOf(Uint8Array);
    expect(proof.length).toBe(128);
    expect(verifyElGamal(dst, pk, c1, dh, proof)).toBe(true);
  });

  it("tampered proof fails verification (low bit of z1 flipped)", () => {
    const { pk, c1, dh } = buildAggregatePoints();
    const dst = new Uint8Array(0);
    const proof = elgamalProve(dst, AGG_BLINDING, AGG_AMOUNT, pk, c1, dh, 1234n, 5678n);

    const tampered = new Uint8Array(proof);
    tampered[64] = (tampered[64] as number) ^ 0x01;

    expect(verifyElGamal(dst, pk, c1, dh, tampered)).toBe(false);
  });

  it("proof with wrong length returns false from verifyElGamal", () => {
    const { pk, c1, dh } = buildAggregatePoints();
    expect(verifyElGamal(new Uint8Array(0), pk, c1, dh, new Uint8Array(127))).toBe(false);
  });

  it("different nonces produce different proofs (nonce domain separation)", () => {
    const { pk, c1, dh } = buildAggregatePoints();
    const dst = new Uint8Array(0);
    const proof1 = elgamalProve(dst, AGG_BLINDING, AGG_AMOUNT, pk, c1, dh, 1234n, 5678n);
    const proof2 = elgamalProve(dst, AGG_BLINDING, AGG_AMOUNT, pk, c1, dh, 9999n, 8888n);

    expect(proof1).not.toEqual(proof2);
    // Both still verify
    expect(verifyElGamal(dst, pk, c1, dh, proof1)).toBe(true);
    expect(verifyElGamal(dst, pk, c1, dh, proof2)).toBe(true);
  });

  it("matches the golden aggregate fixture bytes (r1=1234, r2=5678)", () => {
    // This golden was generated by packages/spike/scripts/generate-aggregate-proof.ts
    // with the same constants and nonces. If this fails, either the elgamal logic
    // drifted from the spike script, or the fixture needs regeneration.
    const { pk, c1, dh } = buildAggregatePoints();
    const dst = new Uint8Array(0);
    const proof = elgamalProve(dst, AGG_BLINDING, AGG_AMOUNT, pk, c1, dh, 1234n, 5678n);

    // Smoke check: verify independently rather than hard-coding the hex (the hex
    // is the committed fixture in packages/spike/test/fixtures/proofAggregateValid.hex).
    expect(verifyElGamal(dst, pk, c1, dh, proof)).toBe(true);

    // Additional structural checks: z1 and z2 scalars should be < RISTRETTO_N.
    const z1 =
      BigInt("0x" + bytesToHex(proof.slice(64, 96).reverse()));
    const z2 =
      BigInt("0x" + bytesToHex(proof.slice(96, 128).reverse()));
    expect(z1).toBeLessThan(RISTRETTO_N);
    expect(z2).toBeLessThan(RISTRETTO_N);
  });

  it("bytesFromBigIntLE roundtrips", () => {
    const sk = bytesFromBigIntLE(AGG_SK, 32);
    expect(sk.length).toBe(32);
    // Check the LE encoding: 12345 = 0x3039, so bytes[0]=0x39, bytes[1]=0x30
    expect(sk[0]).toBe(0x39);
    expect(sk[1]).toBe(0x30);
    // Check it's a valid Ristretto scalar by multiplying G
    const pk = ristretto255.Point.fromHex(bytesToHex(G().toBytes())).multiply(AGG_SK);
    const pk2 = G().multiply(AGG_SK);
    expect(pk.equals(pk2)).toBe(true);
  });
});
