#!/usr/bin/env bash
# scripts/verify-pin.sh
# Assert that all 3 tracked pin locations agree (Story 1.1a AC2, review P3+P4).
# Reads the canonical pin from vendor/contra/PINNED_VERSION (regenerated by
# scripts/regen-pin.sh on `pnpm postinstall`) and checks:
#   1. move/Move.toml  has  rev = "<sha>"  (anchored to that line, not the comment)
#   2. .npmrc           mentions the same sha (in the pin comment)
#   3. vendor/contra submodule HEAD == sha  (already covered by the adapter
#      test, but we assert here too so this script can run in CI without node)
#
# Patching P3: the previous `pnpm verify:pin` matched the SHA in Move.toml's
# comment, not the `rev =` line. Patching P4: the previous script only
# checked 2 of 3 locations (no .npmrc check).
set -eu
set -o pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Regenerate the canonical pin first so the file is fresh.
"$REPO_ROOT/scripts/regen-pin.sh" >/dev/null

PIN_PATH="$REPO_ROOT/vendor/contra/PINNED_VERSION"
SHA=$(grep -E '^Move git sha:\s*[0-9a-f]{40}' "$PIN_PATH" | sed -E 's/^Move git sha:\s*([0-9a-f]{40}).*/\1/')
if [ -z "$SHA" ]; then
  printf '\033[31m✗ verify-pin: no SHA in %s\033[0m\n' "$PIN_PATH" >&2
  exit 1
fi
printf 'canonical SHA: %s\n' "$SHA"

FAIL=0

# 1. move/Move.toml `rev = "..."` line
if grep -Eq "^\s*rev\s*=\s*\"$SHA\"" "$REPO_ROOT/move/Move.toml"; then
  printf '\033[32m✓\033[0m move/Move.toml  rev = "%s"\n' "$SHA"
else
  printf '\033[31m✗\033[0m move/Move.toml  no  rev = "%s"  line found\n' "$SHA" >&2
  FAIL=1
fi

# 2. .npmrc comment mentions the same SHA
if grep -qF "$SHA" "$REPO_ROOT/.npmrc"; then
  printf '\033[32m✓\033[0m .npmrc            mentions %s\n' "$SHA"
else
  printf '\033[31m✗\033[0m .npmrc            does not mention %s\n' "$SHA" >&2
  FAIL=1
fi

# 3. vendor/contra submodule HEAD
if command -v git >/dev/null 2>&1 && [ -e "$REPO_ROOT/vendor/contra/.git" -o -d "$REPO_ROOT/vendor/contra/.git" ]; then
  SUB_SHA=$(git -C "$REPO_ROOT/vendor/contra" rev-parse HEAD)
  if [ "$SUB_SHA" = "$SHA" ]; then
    printf '\033[32m✓\033[0m vendor/contra HEAD  %s\n' "$SUB_SHA"
  else
    printf '\033[31m✗\033[0m vendor/contra HEAD  %s  (expected %s)\n' "$SUB_SHA" "$SHA" >&2
    FAIL=1
  fi
else
  printf '\033[33m!\033[0m git unavailable or submodule not initialised — skipping HEAD check\n' >&2
fi

if [ "$FAIL" -ne 0 ]; then
  printf '\n\033[31m✗ verify-pin: pin drift detected.\033[0m\n' >&2
  exit 1
fi
printf '\n\033[32m✓ verify-pin: all 3 tracked locations agree.\033[0m\n'
